package com.example.starwars;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.widget.ImageView;
import android.widget.TextView;
import com.squareup.picasso.Picasso;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static com.example.starwars.Characters.EXTRA_AFFILIATIONS;
//import static com.example.starwars.Characters.EXTRA_APPRENTICES;
import static com.example.starwars.Characters.EXTRA_ARMAMENT;
import static com.example.starwars.Characters.EXTRA_BORN;
import static com.example.starwars.Characters.EXTRA_BORN_LOCATION;
import static com.example.starwars.Characters.EXTRA_CLASS;
import static com.example.starwars.Characters.EXTRA_CREATOR;
import static com.example.starwars.Characters.EXTRA_CYBERNETICS;
import static com.example.starwars.Characters.EXTRA_DATE_CREATED;
import static com.example.starwars.Characters.EXTRA_DATE_DESTROYED;
import static com.example.starwars.Characters.EXTRA_DEGREE;
import static com.example.starwars.Characters.EXTRA_DESTROYED_LOCATION;
import static com.example.starwars.Characters.EXTRA_DIED;
import static com.example.starwars.Characters.EXTRA_DIED_LOCATION;
//import static com.example.starwars.Characters.EXTRA_EQUIPMENT;
//import static com.example.starwars.Characters.EXTRA_ERA;
import static com.example.starwars.Characters.EXTRA_EYECOLOR;
//import static com.example.starwars.Characters.EXTRA_FORMER_AFFILIATIONS;
import static com.example.starwars.Characters.EXTRA_GENDER;
import static com.example.starwars.Characters.EXTRA_HAIRCOLOR;
import static com.example.starwars.Characters.EXTRA_HEIGHT;
import static com.example.starwars.Characters.EXTRA_HOMEWORLD;
import static com.example.starwars.Characters.EXTRA_KAJIDIC;
import static com.example.starwars.Characters.EXTRA_MANUFACTURER;
import static com.example.starwars.Characters.EXTRA_IMAGE;
import static com.example.starwars.Characters.EXTRA_MASS;
//import static com.example.starwars.Characters.EXTRA_MASTERS;
import static com.example.starwars.Characters.EXTRA_MODEL;
import static com.example.starwars.Characters.EXTRA_NAME;
import static com.example.starwars.Characters.EXTRA_PLATINGCOLOR;
import static com.example.starwars.Characters.EXTRA_PRODUCTLINE;
import static com.example.starwars.Characters.EXTRA_SENSORCOLOR;
import static com.example.starwars.Characters.EXTRA_SKINCOLOR;
import static com.example.starwars.Characters.EXTRA_SPECIES;
import static com.example.starwars.Characters.EXTRA_WIKI;


public class DetailsActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_details);

        Intent intent = getIntent();
        String name = intent.getStringExtra(EXTRA_NAME);
        Integer height = intent.getIntExtra(EXTRA_HEIGHT,0);
        Integer mass = intent.getIntExtra(EXTRA_MASS,0);
        String gender = intent.getStringExtra(EXTRA_GENDER);
        String homeworld = intent.getStringExtra(EXTRA_HOMEWORLD);
        String wiki = intent.getStringExtra(EXTRA_WIKI);
        String image = intent.getStringExtra(EXTRA_IMAGE);
        Integer born = intent.getIntExtra(EXTRA_BORN,0);
        String bornLocation = intent.getStringExtra(EXTRA_BORN_LOCATION);
        Integer died = intent.getIntExtra(EXTRA_DIED,0);
        String diedLocation = intent.getStringExtra(EXTRA_DIED_LOCATION);
        String species = intent.getStringExtra(EXTRA_SPECIES);
        String hairColor = intent.getStringExtra(EXTRA_HAIRCOLOR);
        String eyeColor = intent.getStringExtra(EXTRA_EYECOLOR);
        String skinColor = intent.getStringExtra(EXTRA_SKINCOLOR);
        String cybenretics = intent.getStringExtra(EXTRA_CYBERNETICS);
        List<String> affiliations = Arrays.asList(intent.getStringExtra(EXTRA_AFFILIATIONS));
//        String masters = intent.getStringExtra(EXTRA_MASTERS);
//        String apprentices = intent.getStringExtra(EXTRA_APPRENTICES);
//        String formerAffliations = intent.getStringExtra(EXTRA_FORMER_AFFILIATIONS);
        Integer dateCreated = intent.getIntExtra(EXTRA_DATE_CREATED,0);
        Integer dateDestroyed = intent.getIntExtra(EXTRA_DATE_DESTROYED,0);
        String destroyedLocation = intent.getStringExtra(EXTRA_DESTROYED_LOCATION);
        String creator = intent.getStringExtra(EXTRA_CREATOR);
        String manufacturer = intent.getStringExtra(EXTRA_MANUFACTURER);
        String model = intent.getStringExtra(EXTRA_MODEL);
        String _class = intent.getStringExtra(EXTRA_CLASS);
        String sensorColor = intent.getStringExtra(EXTRA_SENSORCOLOR);
        String platingColor = intent.getStringExtra(EXTRA_PLATINGCOLOR);
//        String equipments = intent.getStringExtra(EXTRA_EQUIPMENT);
        String productLine = intent.getStringExtra(EXTRA_PRODUCTLINE);
        String kajidic = intent.getStringExtra(EXTRA_KAJIDIC);
//        String era = intent.getStringExtra(EXTRA_ERA);
        String degree = intent.getStringExtra(EXTRA_DEGREE);
        String armament = intent.getStringExtra(EXTRA_ARMAMENT);

        TextView textViewCharacter = findViewById(R.id.text_view_character_detail);
        TextView textViewHeight = findViewById(R.id.height);
        TextView textViewMass = findViewById(R.id.mass);
        TextView textViewGender = findViewById(R.id.gender);
        TextView textViewHomeworld = findViewById(R.id.homeworld);
        TextView textViewWiki = findViewById(R.id.wiki);
        ImageView imageView = findViewById(R.id.image_view_detail);
        TextView textViewBorn = findViewById(R.id.born);
        TextView textViewBornLocation = findViewById(R.id.born_location);
        TextView textViewDied = findViewById(R.id.died);
        TextView textViewDiedLocation = findViewById(R.id.died_location);
        TextView textViewSpecies = findViewById(R.id.species);
        TextView textViewHaircolor = findViewById(R.id.hair);
        TextView textViewEyeColor = findViewById(R.id.eye);
        TextView textViewSkinColor = findViewById(R.id.skin);
        TextView textViewCyber = findViewById(R.id.cyber);
        TextView textViewAffiliations = findViewById(R.id.affiliations);
//        TextView textViewMasters = findViewById(R.id.masters);
//        TextView textViewApprentices = findViewById(R.id.apprentices);
//        TextView textViewFormer = findViewById(R.id.former);
        TextView textViewDateCreated = findViewById(R.id.date_created);
        TextView textViewDateDestroyed = findViewById(R.id.date_destroyed);
        TextView textViewDestroyed = findViewById(R.id.destroyed);
        TextView textViewCreator = findViewById(R.id.creator);
        TextView textViewManufacturer = findViewById(R.id.manufacturer);
        TextView textViewModel = findViewById(R.id.model);
        TextView textViewClass = findViewById(R.id.class_);
        TextView textViewSensor = findViewById(R.id.sensor);
        TextView textViewPlating = findViewById(R.id.plating);
//        TextView textViewEquipments = findViewById(R.id.equipments);
        TextView textViewProduct = findViewById(R.id.product);
        TextView textViewKajidic = findViewById(R.id.kajidic);
//        TextView textViewEra = findViewById(R.id.era);
        TextView textViewDegree = findViewById(R.id.degree);
        TextView textViewArmament = findViewById(R.id.armament);

        textViewCharacter.setText(name);
        textViewHeight.setText("Height: " + height);
        textViewMass.setText("Mass: " + mass);
        textViewGender.setText(gender);
        textViewHomeworld.setText(homeworld);
        textViewWiki.setText(wiki);
        Picasso.get().load(image).fit().centerCrop().into(imageView);
        textViewBorn.setText("Born: " + born);
        textViewBornLocation.setText(bornLocation);
        textViewDied.setText("Died: " + died);
        textViewDiedLocation.setText(diedLocation);
        textViewSpecies.setText(species);
        textViewHaircolor.setText(hairColor);
        textViewEyeColor.setText(eyeColor);
        textViewSkinColor.setText(skinColor);
        textViewCyber.setText(cybenretics);
        textViewAffiliations.setText(affiliations);
//        textViewMasters.setText(masters);
//        textViewApprentices.setText(apprentices);
//        textViewFormer.setText(formerAffliations);
        textViewDateCreated.setText("Date created: " + dateCreated);
        textViewDateDestroyed.setText("Date destroyed: " + dateDestroyed);
        textViewDestroyed.setText(destroyedLocation);
        textViewCreator.setText(creator);
        textViewManufacturer.setText(manufacturer);
        textViewModel.setText(model);
        textViewClass.setText(_class);
        textViewSensor.setText(sensorColor);
        textViewPlating.setText(platingColor);
//        textViewEquipments.setText(equipments);
        textViewProduct.setText(productLine);
        textViewKajidic.setText(kajidic);
//        textViewEra.setText(era);
        textViewDegree.setText(degree);
        textViewArmament.setText(armament);
    }
}
